# Generated by Django 3.1.1 on 2020-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201028_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
