# Generated by Django 3.1.1 on 2020-12-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
