# Generated by Django 3.1.1 on 2020-12-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='user_image',
            field=models.ImageField(default='profile.png', upload_to='userimage'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog.jpg', upload_to='images'),
        ),
    ]
