# Generated by Django 3.1.1 on 2020-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201210_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default_blog.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='user_image',
            field=models.ImageField(default='default_profile.jpg', upload_to='userimage'),
        ),
    ]
