# Generated by Django 3.1.1 on 2020-12-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201210_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default_blog.jpg', upload_to='images/'),
        ),
    ]
