# Generated by Django 3.1.1 on 2020-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20201211_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='user_image',
            field=models.ImageField(default='default_profile.jpg', upload_to='userimage/'),
        ),
    ]
